//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinalProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Products
    {
        [DisplayName("產品編號")]
        public int Id { get; set; }
        [DisplayName("品名")]
        public string Name { get; set; }
        [DisplayName("單價")]
        public int Price { get; set; }
        public string ImageURL { get; set; }
        [DisplayName("商品敘述")]
        public string Description { get; set; }
        [DisplayName("商品上傳日期")]
        public System.DateTime PublishDate { get; set; }
        [DisplayName("商品數量")]
        public short Quantity { get; set; }
        [DisplayName("賣家")]
        public string UserName { get; set; }
    }
}
